### ISSUE TITLE
[RFE] add a toleration for deamonsets on K3s

### ISSUE THREAD

**Issue by andi-blafasl** [flatcar/flatcar-linux-update-operator#175]
## Current situation

If you have a K3s Cluster with dedicated controlplane nodes the recommended way to taint nodes is [CriticalAddonsOnly=true:NoExecute](https://docs.k3s.io/installation/ha#2-launch-server-nodes)

## Impact

If you deploy with the example files from this repo, the "flatcar-linux-update-agent" pods do not run on the control-plane nodes.

## Ideal future situation

"flatcar-linux-update-agent" pods are running on all K3s nodes

## Implementation options

Add the following toleration like k3s does for it's own core Services like [traefik](https://github.com/k3s-io/k3s/blob/b276b58175e914a24b93f56751335b55cd7a60ab/manifests/traefik.yaml#L32-L33)

```yaml
    - key: "CriticalAddonsOnly"
      operator: "Exists"
```

## Additional information

I tested this on my k3s cluster by editing the deployment and daemonset and the pods started on the control-plane immediately.

**Comment by invidian** [comment]
Hm, I guess this toleration could also be applied via kustomize. `CriticalAddonsOnly` Toleration seem k3s specific, I'm not sure if we want to support every possible k8s distro by default, as this toleration does not seem "standard", as recommended in official K8s docs.

The deployment files in the repository resides in `examples` for a reason after all.

**Comment by invidian** [comment]
No worries. Usually manifests provided by the project must be customized anyway for people's cluster, as there is simply too many configuration options to satisfy everyone by default.

One of the convenient ways doing this is using [kustomize](https://kubernetes.io/docs/tasks/manage-kubernetes-objects/kustomization/), which as far as I know is kind of official way of doing this, which we support since #87. 

 A popular alternative is using [helm](https://helm.sh) which we do not support yet (issue #24).

**Comment by invidian** [comment]
I will close this for the time being. @andi-blafasl let me know if you need more help.
